WIP: Issue 79
DiscordTime/sticky-sessions-server pull request #81
Opened 2019-06-20 20:39 UTC by ehammo

Update SessionRepository to use new db
Update DBFactory to create a single db
Update config to the single db type
Create Session model
Create Session Mapper
Update Session Router to class
Create GenericRouter

TODO: tests

2019-06-21 21:08 UTC, rodrigoperazzo commented on index.js
> +// console.log(config)
Please log only on production environment.

2019-06-21 21:12 UTC, rodrigoperazzo commented on src/controllers/index.js
> +  constructor (notesRepository, sessionRepository) {
Let's use just one name pattern (plural vs singular). I would suggest change `notesRepository` to `noteRepository`.

2019-06-21 21:13 UTC, rodrigoperazzo commented on src/controllers/sessionController.js
> +    console.log('Validating')
Please remove all "validate" logs.

2019-06-21 21:16 UTC, rodrigoperazzo commented on src/environment/FirestoreDB/index.js
> +          if (item === 'id') {
I suggest replacing `item` by `field` to improve code reading.

2019-06-21 21:19 UTC, rodrigoperazzo commented on src/repositories/sessionsRepository/index.js
> +  async getAllSessions (session) {
Why getAllSessions receives a session?

2019-06-21 21:21 UTC, rodrigoperazzo commented on src/router/index.js
> +    var sessionsRouter = new SessionRouter(this.controllers.getSessionsController())
Rename variable to sessionRouter

2019-06-21 21:26 UTC, rodrigoperazzo commented on src/router/router.js
> +      res.status(400)
I suggest rewriting all `res.send()` cases here to only one at the end of the function. That's should improve readability.

2019-06-21 21:35 UTC, rodrigoperazzo commented on src/router/router.js
> +    if (response.message) {
Move everything after try/catch inside the try block or create a function for all responses different from status `400`.

2019-06-21 21:36 UTC, rodrigoperazzo commented on src/router/router.js
> +      res.send({ 'error': response.message })
No return here?

2019-06-21 21:38 UTC, rodrigoperazzo requested changes
Added some comments.

2019-06-25 16:55 UTC, rodrigoperazzo commented on src/environment/FirestoreDB/mapper/index.js
> +module.exports.mapSnapshotToArrayAsync = function (snapshot) {
I would rename it as `mapSnapshotToArray` since it is not an async function anymore.

2019-06-25 16:57 UTC, rodrigoperazzo commented on src/environment/FirestoreDB/mapper/index.js
> +function mapDocumentToData (doc) {
`mapDocumentToDomain` would be a better name.

2019-06-25 16:58 UTC, rodrigoperazzo commented on src/router/router.js
> +    if (response.message) {
If the thrown error could contain status code and message attributes we wouldn't need to handle `response.message` case separately.

2019-06-25 22:11 UTC, rodrigoperazzo approved these changes

2019-06-26 02:27 UTC, viniciusalbuquerque approved these changes

2019-06-27 15:21 UTC, merged