Add Teams endpoint
DiscordTime/sticky-sessions-server pull request #86
Opened 2020-02-06 21:22 UTC by CarlosRodrigo

2020-02-06 21:36 UTC, jvpessoa10 reviewed
Please, checkout to dev first.

When deleting a team, this routine should delete team's meetings too?

2020-02-23 20:55 UTC, viniciusalbuquerque requested changes
A minor concern

2020-02-23 20:55 UTC, viniciusalbuquerque commented on src/controllers/teamController.js
> +      topics: Joi.array().items(Joi.string()).required(),
I think you didn't mean `topics` here. Maybe you mean `members`. What about the `admin`?

2020-02-23 20:55 UTC, viniciusalbuquerque commented on src/controllers/teamController.js
> +      topics: Joi.array().items(Joi.string()).required()
Same as above comment.

2020-10-23 13:44 UTC, closed without merging